class Schema(object):
	E_ORDER = ['source', 'state', 'election', 
			'locality', 'precinct', 'precinct_split', 
			'election_administration', 'election_official', 
			'polling_location', 'early_vote_site', 'contest', 
			'electoral_district', 'ballot', 'candidate', 
			'referendum', 'custom_ballot', 'ballot_response', 
			'street_segment']
	ADDRESS_TYPE = ['non_house_address', 'address', 
			'physical_address', 'mailing_address']
	E_DICT = {'electoral_district': ['name', 'type', 'number'], 
			'referendum': ['title', 'subtitle', 'brief', 'text', 
					'pro_statement', 'con_statement', 
					'passage_threshold', 'effect_of_abstain'], 
			'polling_location': ['address_line2', 'address_line3', 
						'address_city', 'address_line1', 
						'address_state', 'address_location_name', 
						'address_zip', 'directions', 
						'polling_hours', 'photo_url'], 
			'election': ['date', 'election_type', 'state_id', 
					'statewide', 'registration_info', 
					'absentee_ballot_info', 'results_url',
					 'polling_hours', 'election_day_registration',
					 'registration_deadline', 'absentee_request_deadline'], 
			'ballot': ['referendum_id', 'candidate_id',
					'custom_ballot_id', 'write_in', 'image_url'], 
			'candidate': ['name', 'party', 'candidate_url', 
					'biography', 'phone', 'photo_url',
					 'filed_mailing_address_location_name', 
					'filed_mailing_address_state', 
					'filed_mailing_address_line1', 
					'filed_mailing_address_line3', 
					'filed_mailing_address_line2', 
					'filed_mailing_address_zip', 
					'filed_mailing_address_city', 
					'email', 'sort_order'], 
			'locality': ['name', 'state_id', 'type', 
					'election_administration_id', 'early_vote_site_id'], 
			'custom_ballot_ballot_response': ['custom_ballot_id', 
								'ballot_response_id', 
								'sort_order'], 
			'election_administration': ['name', 'eo_id', 
							'ovc_id', 'physical_address_state', 
							'physical_address_city', 'physical_address_line3', 
							'physical_address_line2', 'physical_address_line1', 
							'physical_address_location_name', 'physical_address_zip', 
							'mailing_address_state', 'mailing_address_line1', 
							'mailing_address_line2', 'mailing_address_line3', 
							'mailing_address_location_name', 'mailing_address_zip', 
							'mailing_address_city', 'elections_url', 
							'registration_url', 'am_i_registered_url', 
							'absentee_url', 'where_do_i_vote_url', 
							'what_is_on_my_ballot_url', 'rules_url', 
							'voter_services', 'hours'], 
			'state': ['name', 'election_administration_id', 'early_vote_site_id'], 
			'street_segment': ['start_house_number', 'end_house_number',
						 'odd_even_both', 'start_apartment_number', 
						'end_apartment_number', 'non_house_address_address_direction', 
						'non_house_address_street_name', 'non_house_address_house_number_prefix', 
						'non_house_address_city', 'non_house_address_street_suffix', 
						'non_house_address_state', 'non_house_address_street_direction', 
						'non_house_address_house_number_suffix', 'non_house_address_zip', 
						'non_house_address_apartment', 'non_house_address_house_number', 
						'precinct_id', 'precinct_split_id'], 
			'precinct_split': ['name', 'precinct_id', 'electoral_district_id',  
						'polling_location_id', 'ballot_style_image_url'], 
			'custom_ballot': ['heading'], 
			'precinct': ['name', 'number', 'locality_id',
					'electoral_district_id', 'ward', 
					'mail_only', 'polling_location_id',
					'early_vote_site_id', 'ballot_style_image_url', 
							'electoral_district_id'], 
			'contest': ['election_id', 'electoral_district_id', 
					'type', 'partisan', 'primary_party', 
					'electorate_specifications', 'special', 
					'office', 'filing_closed_date', 
					'number_elected', 'number_voting_for', 
					'ballot_id', 'ballot_placement'], 
			'referendum_ballot_response': ['referendum_id', 
							'ballot_response_id', 
							'sort_order'], 
			'ballot_response': ['text', 'sort_order'], 
			'early_vote_site': ['name', 'address_line2', 
						'address_line3', 'address_city',
						'address_line1', 'address_state', 
						'address_location_name', 'address_zip', 
						'directions', 'voter_services', 
						'start_date', 'end_date', 
						'days_times_open'], 
			'source': ['name', 'vip_id', 'datetime', 
					'description', 'organization_url', 
					'feed_contact_id', 'tou_url'], 
			'election_official': ['name', 'title', 'phone', 
						'fax', 'email']}
	UNBOUNDED = {'state': set(['early_vote_site_id']),
			'locality': set(['early_vote_site_id']),
			'precinct': set(['electoral_district_id', 
						'polling_location_id',
						'early_vote_site_id']),
			'precinct_split': set(['electoral_district_id',
						'polling_location_id']),
			'ballot': set(['candidate_id'])}
	ADDRESS_TYPES = ['address', 'non_house_address',
				'physical_address', 'mailing_address']

class Output(object):
	VERSION = "3.0"
	SCHEMA_URL = "https://github.com/votinginfoproject/vip-specification/blob/master/vip_spec_v{0}.xsd".format(VERSION)
	HEADER = '<?xml version="1.0" encoding="utf-8"?>\n<vip_object xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="{0}" schemaVersion="{1}">'.format(SCHEMA_URL, VERSION)
	FOOTER = "</vip_object>"
	XML_FILE = "vipFeed-{0}-2012-11-06.xml"
